image: debian:latest

stages:
  # - test
  - build

.eslint:
  stage: test
  image: registry.gitlab.com/pipeline-components/eslint:latest
  script:
    - npx eslint --fix backend


# include:
#   - template: Jobs/Secret-Detection.gitlab-ci.yml

build:
  stage: build
  image: docker:28.2.2-dind
  script:
    # - docker version
    - docker build -f Dockerfile.debian . -t debian_biblio:latest
