image: debian:latest

stages:
  - meow
  - lint

# meow-job:
#   stage: meow
#   before_script:
#     - apt-get update -qq
#     - apt-get install -y cowsay
#   script:
#     - /usr/games/cowsay "Meoooow"

eslint:
  stage: lint
  needs: []
  image: registry.gitlab.com/pipeline-components/eslint:latest
  script:
    - npx eslint --fix backend


include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml