image: docker:latest

services:
  - name: docker:28.2.2-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""


stages:
  - test
  - build

.eslint:
  stage: test
  image: registry.gitlab.com/pipeline-components/eslint:latest
  script:
    - npx eslint --fix backend


# include:
#   - template: Jobs/Secret-Detection.gitlab-ci.yml

build:
  stage: build
  script:
    - docker info
    - docker build -f Dockerfile.debian . -t debian_biblio:latest
