image: debian:latest

stages:
  # - test
  - build

.eslint:
  stage: test
  image: registry.gitlab.com/pipeline-components/eslint:latest
  script:
    - npx eslint --fix backend


# include:
#   - template: Jobs/Secret-Detection.gitlab-ci.yml

build:
  stage: build 
  image: docker:24
  services:
    - docker:24-dind # dind pour docker in docker : parce qu'on va utiliser des commandes `docker` depuis un conteneur !

  script:
    # - docker version
    - docker build -f backend/Dockerfile.debian . -t debian_biblio:latest
