image: debian:latest

stages:
  - meow
  - test
  - build

# meow-job:
#   stage: meow
#   before_script:
#     - apt-get update -qq
#     - apt-get install -y cowsay
#   script:
#     - /usr/games/cowsay "Meoooow"

.eslint:
  stage: test
  needs: []
  image: registry.gitlab.com/pipeline-components/eslint:latest
  script:
    - npx eslint --fix backend


include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

build:
  stage: build
  image: docker:28.2.2
  script:
    - docker build -f Dockerfile.debian . -t debian_biblio:latest
