services:
  api:
    image: registry.gitlab.com/inesbdl-group/inesbdl-docker-avance/gestion-biblio-debian:631aa079
    build:
      context: ./backend
      # dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile
      # dockerfile: Dockerfile.debian
      target: dev
    ports:
      - ${PORT_BACK}:${PORT_BACK}
    env_file: .env
    volumes:
      - ./database/bookshelf.sqlite:/database/bookshelf.sqlite
      - ./backend/controllers/:/backend/
      - ./backend/models/:/backend/
      - ./backend/routes/:/backend/
      - ./backend/services/:/backend/
      - ./backend/app.js:/backend/app.js
      #- ./backend:/backend
    command:
      sleep 9999

  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${PORT_FRONT}:${PORT_FRONT}
    env_file: .env
