FROM debian:bookworm AS base

RUN apt-get update && apt-get install -y nodejs npm

WORKDIR /backend

COPY package.json .

RUN npm install

FROM base AS dev

# COPY package.json .

# RUN npm install

ENV ENVIRONMENT=dev

CMD ["node", "app.js"]

FROM base AS prod

ENV ENVIRONMENT=prod

COPY . .

# RUN npm install

ENTRYPOINT ["node", "app.js"]
